# Generated by Django 3.1.7 on 2021-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField(max_length=3)),
                ('datetime', models.DateField(verbose_name='Detected date')),
                ('time', models.TimeField(verbose_name='Detected time')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dataset_id', models.IntegerField(max_length=3)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
