# Generated by Django 3.1.7 on 2021-03-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detected',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='dataset_id',
        ),
    ]
