# Generated by Django 3.1.7 on 2021-04-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210329_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detected',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterModelTable(
            name='detected',
            table='detected',
        ),
    ]
